### ISSUE TITLE
arm64 container availability

### ISSUE THREAD

**Issue by t4nki** [kittyandrew/grafana-to-ntfy#8]
Hi,

This project would look great in my homelab, unfortunately this is only available for amd64 architecture

Do you have any plans releasing this container on arm64 ?

Ntfy and Grafana both run great on Raspberry Pi ans your project would fit nicely between the two.

I have absolutely no experience regarding Rust and coding in general, so I would be of absolutely no help, except for testing

Keep the community posted about this

Regards

**Comment by kittyandrew** [comment]
Hello,
I've updated the build to multi-arch and now `kittyandrew/grafana-to-ntfy:latest` should be available for your use.

I don't have devices to test these, so please provide feedback on whether it works for you.

**Comment by t4nki** [comment]
Hi,

That's great to hear, i'll test it right away!

**Comment by t4nki** [comment]
Hi again,

I've just tried to run arm64 container with podman and ansible to no avail
Here's my playbook snippet about grafana-to-ntfy

```
- name: Déploiement de Grafana2Ntfy
  containers.podman.podman_container:
    name: grafana2ntfy
    image: docker.io/kittyandrew/grafana-to-ntfy:latest
    label:
      io.containers.autoupdate=registry
      PODMAN_SYSTEMD_UNIT=pod_metrics.service
    env:
      TZ: 'Europe/Paris'
      NTFY_URL: "https://{{ ntfy_sub }}/monitoring"
      BATUH_USER: "{{ g2n_login }}"
      BATUH_PASS: "{{ vault_g2n_passwd }}"
    volumes:
      - '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'
    state: present
    restart_policy: "no"
    pod: "metrics"
```

As you can see everything is in a pod dedicated to metrics

Anyways, here's the error I get from the container when I start it :+1: 
```
{"msg":"exec container process `/usr/src/app/./grafana-to-ntfy`: Exec format error","level":"error","time":"2023-05-29T13:29:52.357691Z"}
```

hope you can do something about it,
cheers
